version: '3.8'
volumes:
  postgres_data:
  static_volume:
services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: nortonts/yamdb:latest
    build: .
    restart: always
    volumes:
      - static_volume:/code/static/
    command: gunicorn api_yamdb.wsgi:application --bind 127.0.0.1:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    build: ./nginx
    restart: always
    ports: 
      - "80:80"
    depends_on:
      - web
    volumes:
      - static_volume:/code/static/